config/routes.rb
Blog::Application.routes.draw do
  
  get 'welcome' => 'welcome#index'

  get 'angular' => 'angular#index'
  get 'angtwo' => 'angular#angtwo'

  resources :posts do 
    resources :comments
  end  
  

   root 'welcome#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :post_id
  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def index   
  end
  def angtwo  
  end
  
end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/angular/angtwo.html.erb
<% content_for :footer do %>
	<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js'  %>
	<%= javascript_include_tag 'angular/angtwo' %>
<% end %>


<div ng-app="appTwo">

	<div ng-controller="MoreController">
		<h1>Incrementing and stopping $watcher</h1>
		<p>{{valuetest}}</p>
		<p>Num equal: {{ num }}</p>
		<p>Num Array is: {{ nums }}</p>
		<button class="btn btn-primary" ng-click="increment()">Increment & add to Array</button>
		<button class="btn btn-danger" ng-click="breakit()">Break it</button>
		<br />
		<hr />
		<h1>NG-cloak</h1>
		<p ng-cloak> {{somedata}} </p>
		<p>Additionally do not forget to add proper CSS for ng-cloak to work properly:</p>
		<p> [ng\cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {display: none !important} </p>
		<style>[ng\cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {display: none !important} </style>
		<br />
		<hr />
	</div>
	
	
</div>


<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js"></script> 

app/views/angular/index.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'angular/index' %>
<% end %>
<% content_for :footer do %>
	<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js'  %>
	<%= javascript_include_tag 'angular/index' %>
<% end %>
<div class="container">
 <div ng-app="app">
	<h1>
		First Controller: ng-click, ng-show
	</h1>
		<p>
		Example of Angular bombating: {{ 12 + 5 }}
		</p>
	<div ng-controller="MainController">
		<p>Value is equal to: {{val}} </p>
		<p> {{ func() }}</p>
		<button class="btn btn-primary" ng-click="inc()" >Increment Value</button>
		<h2>ng-show & hide</h2>
		<p ng-show="even">The value choosen is: Even</p>
		<p ng-hide="even">The value choosen is: Odd</p>
	</div>
	<br />
	<hr />
	<h1>Second Controller: ng-model, $index, ng-include</h1>	
	<div ng-controller="SecController">
		<p ng-class="[classVar, 'italic']">Elements of Array</p>
		<div ng-repeat="element in myarr track by $index">
			{{element}}	
			<span ng-show="$first">first</span>	
			<span ng-show="$middle">middle</span>
			<span ng-show="$last">last</span>
			<span ng-show="$even">even</span>
			<span ng-show="$odd">odd</span>	
		</div>
		<div ng-repeat="user in users">
			<strong>{{user.name}}</strong>: {{user.age}}
		</div>
		
		<div>
			<h4 ng-class="{orange: classVar2, italic: classVar2}">Hello there!</h4>
		</div>
		
		<!-- Include demo -->
		<div ng-include="'test.html'"></div>
		<script type="text/ng-template" id="test.html">
			<h1>My template</h1>
		</script>
		
		<!-- ng-model demo -->
		<h4>Input 1</h4>
		<input ng-model="mydata" />
		<h5>{{mydata}}</h5>
		<br />
		<br />
		<h4>Input 2</h4>
		<input ng-model="mydata2" />
		<button ng-click="mydata">Add data</button>
		<h5>Your data is: {{mydata2}}</h5>
		
	</div>
	<br />
	<hr />
	<h1>Third Controller: Scope.$Watch</h1>
	<div ng-controller="ThirdController">
		<input ng-model="datathree.val" />
		<h4>{{datathree.val}}</h4>
		<span ng-show="datathree.toolong" style="color:red;">Name is too long!</span>
		<br />
		<hr />
		
	</div>
	
 </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js"></script> 

app/views/comments/_comment.html.erb
		<%= div_for comment do %>
			<p>
				<strong> Posted <%= time_ago_in_words(comment.created_at) %> </strong></br>
				<%= h(comment.body) %>
			</p>
		<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= welcome_path %>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= angular_path %>">AngularJS Basic</a></li>
        <li><a href="<%= posts_path %>">Blog - Coursera web App Course </a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">AngularJS Tuts <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%= angular_path %>">First</a></li>
            <li><a href="<%= angtwo_path %>">Second</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

<footer>
	
</footer>

<% yield :after_footer %>
</body>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


 <h2>Comments</h2>
  <div id="comments">
<%= render :partial => @post.comments.reverse %>
   </div>
   <hr />

<%= form_for([@post, Comment.new], remote: true) do |f| %>
   	<p>
   		<%= f.label :body, "New Comment" %></br>
   		<%= f.text_area :body  %>
   	</p>
   	<p>
   		<%= f.submit "Add Comment" %>
   	</p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>
	Purpose disclaimer
</h1>
<h4>This application is intended only for practice purposes only.</h4>	